### ISSUE TITLE
Bug in week numbers on the mini-calendar starting 2024-W13

### ISSUE THREAD

**Issue by elaine-threepwood** [YU000jp/logseq-plugin-show-weekday-and-week-number#137]
I see the label "W13" repeated both for week 13 (March 25-31) and week 14 (April 1-7). Starting from there, all the following week numbers are wrong because of this

![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/164868365/95698f9d-5b68-4b1b-a9b2-6b50e34e53d5)

**Comment by YU000jp** [comment]
Sorry, I couldn't find a way to reproduce the bug. Once I figure out how to reproduce this bug, I plan to modify the calculation method for calculating the week number. Probably, I'm going to change the day of the week to identify the week number.
Did you choose ISO format and, any start of the week config?

**Comment by YU000jp** [comment]
There may also be a time zone effect. Checking it up now.

**Comment by AvanBerne** [comment]
btw, I am using ISO format, and all other relevant settings are on default. The only other thing I noticed is that the weekend between W13 and W14 is a holiday weekend, where both the Sunday and the Monday are a holiday in my region (NL).
Also, since [elaine-threepwood](https://github.com/elaine-threepwood) hasn't answered - from their screenshot it seems they are using a southern european language (possibly Italian), so I would guess they are also using ISO(EU) week format.

**Comment by YU000jp** [comment]
> btw, I am using ISO format, and all other relevant settings are on default. The only other thing I noticed is that the weekend between W13 and W14 is a holiday weekend, where both the Sunday and the Monday are a holiday in my region (NL).
> Also, since [elaine-threepwood](https://github.com/elaine-threepwood) hasn't answered - from their screenshot it seems they are using a southern european language (possibly Italian), so I would guess they are also using ISO(EU) week format.

I will verify based on your information. To prevent other bugs from occurring, I plan to reproduce and isolate this bug under similar conditions as much as possible.
