### ISSUE TITLE
Error displayed in the page for month naming

### ISSUE THREAD

**Issue by yoghurtdewdew** [YU000jp/logseq-plugin-show-weekday-and-week-number#67]
When the file name contains dates, it is automatically recognized, which is also pretty good. But when the file name is month, it is recognized as the wrong month, week, and days.
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/63794438/a089367b-5250-4b48-824e-9bfd611106a8)
BTW, I see that there is a weekly note feature. Is it possible to link the weekly note with the journals of that week? When I clicked into my weekly note, I will see a blank space in it and felt like I couldn't summarize it perfectly. Is it possible to have a monthly note feature and add month's wikipage/tag to the weekly note to link the months and weeks?

**Comment by YU000jp** [comment]
1. Change it so that it is not displayed on pages other than journals.

1. I believe it may be necessary to include an Advanced Query on the Weekly Journal page, but I am not familiar with it. Alternatively, I think your desired outcome could possibly be achieved by combining it with plugins like Full House Templates, but I haven't tried it yet.

1. There are several issues that need to be addressed in order to implement the Monthly Journal feature, and they have not been resolved. It is due to the various date formats available in Logseq. If a date format other than yyyy/mm/dd is being used, pages such as 2023/07 will become isolated."
